# Site
name: "Queer in Wurzen"
title: "Queer in Wurzen"
description: "Queere Menschen in Wurzen - und ihre Geschichten."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 
disqus: 'queerInWurzen'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  timber:
    name: Timber
    display_name: Timber
    avatar: 'assets/images/timber.png'
    description: "Nichtbinär in Wurzen."
  janina:
    name: Janina
    display_name: Janina
    avatar: 'assets/images/janina.png'
    description: "Pansexuell in Wurzen."
  gwen:
    name: Gwen
    display_name: Gwen
    avatar: 'assets/images/gwen.png'
    description: "Agender in Wurzen."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE, README.md, Gemfile, Gemfile.lock]
