# Site
name: "Queer in Wurzen"
title: "Queer in Wurzen"
description: "Queere Menschen in Wurzen - und ihre Geschichten."
logo: 'assets/images/logo.webp'
favicon: 'assets/images/favicon.ico'
baseurl: 
disqus: 'queerInWurzen'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  timber:
    name: Timber
    display_name: Timber (dey/deren)
    avatar: 'assets/images/timber.webp'
    description: "Nichtbinär in Wurzen."
  janina:
    name: Janina
    display_name: Janina (sie/alle)
    avatar: 'assets/images/janina.webp'
    description: "Pansexuell in Wurzen."
  gwen:
    name: Gwen
    display_name: Gwen (keine Pronomen)
    avatar: 'assets/images/gwen.webp'
    description: "Agender in Wurzen."
  fia:
    name: Fia
    display_name: Fia (sie/ihr)
    avatar: 'assets/images/fia.webp'
    description: "Polyamor in Wurzen."
  aleks:
    name: Aleks
    display_name: Aleks (they/she)
    avatar: 'assets/images/aleks.webp'
    description: "Nonbinary in Wurzen."
  astrid:
    name: Astrid
    display_name: Astrid (sie/ihr)
    avatar: 'assets/images/astrid.webp'
    description: "Bisexuell in Wurzen."
  lisa:
    name: Lisa
    display_name: Lisa (sie/ihr)
    avatar: 'assets/images/lisa.webp'
    description: "Trans* in Wurzen."
  rocinante:
    name: Rocinante
    display_name: Rocinante
    avatar: 'assets/images/rocinante.webp'
    description: "Trans* in Wurzen."
  beiunsdochnicht:
    name: Bei uns doch nicht!
    display_name: Bei uns doch nicht!
    avatar: 'assets/images/beiunsdochnicht.webp'
    description: "Podcast: Queersein und Queerfeindlichkeit in Wurzen."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
  - jekyll-redirect-from
    
# Pagination 
paginate: 10
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE, README.md, Gemfile, Gemfile.lock]
