# Site
name: "Queer in Wurzen"
title: "Queer in Wurzen"
description: "Queere Menschen in Wurzen - und ihre Geschichten."
logo: 'assets/images/logo.svg'
favicon: 'assets/images/favicon.ico'
baseurl: 
disqus: 'queerInWurzen'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  timber:
    name: Timber
    display_name: Timber (dey/deren)
    avatar: 'assets/images/timber.svg'
    description: "Nichtbinär in Wurzen."
  janina:
    name: Janina
    display_name: Janina (sie/alle)
    avatar: 'assets/images/janina.svg'
    description: "Pansexuell in Wurzen."
  gwen:
    name: Gwen
    display_name: Gwen (keine Pronomen)
    avatar: 'assets/images/gwen.svg'
    description: "Agender in Wurzen."
  fia:
    name: Fia
    display_name: Fia (sie/ihr)
    avatar: 'assets/images/fia.svg'
    description: "Polyamor in Wurzen."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE, README.md, Gemfile, Gemfile.lock]
