# Site
name: "Queer in Wurzen"
title: "Queer in Wurzen"
description: "Queere Menschen in Wurzen - und ihre Geschichten."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 
disqus: 'queerInWurzen'
include: ["_pages"]
permalink: /:title/
email: TODO

# Authors
authors:
  timber:
    name: Timber
    display_name: Timber
    avatar: 'assets/images/avatar-timber.png'
    email: timber@systemli.org
    description: "Nichtbinär in Wurzen."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE, README.md, Gemfile, Gemfile.lock]
